### PR TITLE
Fix `Cannot redeclare ClarkWinkelmann\MassActions\hasGlobalOrScopedPermission()` error

### PR DESCRIPTION
**Pull request by rob006**
It looks like `extend.php` may be called multiple times and defining classes or functions in this file will create errors. I encountered this error while disabling this plugin.

### CODE REVIEW

**Comment by clarkwinkelmann** [comment]
Interesting, I never saw that error, I'll check it out.

Another solution would be simply to wrap the method in `method_exists`, Wordpress-style.

**Comment by rob006** [comment]
IMO declaring global symbols in regular code is just bad practice overall (AFAIK there is a PSR rule which prohibits that). If you don't want to use closure in that way, I suggest to just declare helper class with static method.

**Comment by clarkwinkelmann** [comment]
But it's a namespaced function here, which is why I used this solution originally. I wouldn't have made a global method, that's for sure.

I'll see what I prefer after I give it a try locally.

**Comment by rob006** [comment]
`ClarkWinkelmann\MassActions\hasGlobalOrScopedPermission()` **is** a global symbol - you can declare it only once and after declaration it is available from everywhere.

**Comment by rob006** [comment]
Also, PSR rule I was talking about: https://www.php-fig.org/psr/psr-1/

> Files SHOULD either declare symbols (classes, functions, constants, etc.) or cause side-effects (e.g. generate output, change .ini settings, etc.) but SHOULD NOT do both.

**Comment by clarkwinkelmann** [comment]
I have moved all the code to a dedicated serializer attributes class, with the lines that were added in recent updates it was starting to make sense to do that anyway.

I did this in a separate commit b1082b40deb4a8ae5795ca6575964363d86ba2ff and added you as co-author.

Thanks!

**Pull request closed without merging**
